/*
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                               SQL SCRIPT FOR EXPLORATORY DATA ANALYSIS
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*/

/* dimension exploration */

-- explore all countries
select distinct country
from gold.dim_customers;

-- explore all categories 'major divisions'
select distinct category,subcategory
from gold.dim_products;


/* date exploration */

-- find date of first and last order 
-- how many months of sales
select min(order_date) as first_order_date,
max(order_date) as last_order_date,
timestampdiff(month,min(order_date),max(order_date)) as range_months
from gold.fact_sales;

-- find youngest and oldest customer
select
min(birth_date) oldest_birthdate,
timestampdiff(year,min(birth_date),curdate()) oldest_age,
max(birth_date) youngest_birthdate,
timestampdiff(year,max(birth_date),curdate()) youngest_age
from gold.dim_customers;


/* measure exploration */

-- find total sales
select sum(sales) as total_sales from gold.fact_sales;

-- find how many items sold
select sum(quantity) as total_quantity from gold.fact_sales;

-- find average selling price
select avg(price) as average_price from gold.fact_sales;

-- find total number of orders
select count(distinct order_number) as total_orders from gold.fact_sales;

-- find total number of customers
select count(distinct customer_id) as total_customers from gold.fact_sales;

-- find total number of products
select count(distinct product_name) as total_products from gold.dim_products;

-- create report that shows all key metrics of the business
select 'Total sales' as measure_name,sum(sales) as measure_value from gold.fact_sales
union all
select 'Total quantity' as measure_name,sum(quantity) as measure_value from gold.fact_sales
union all
select 'Average price' as measure_name,round(avg(price)) as measure_value from gold.fact_sales
union all
select 'Number of orders' as measure_name,count(distinct order_number) as measure_value from gold.fact_sales
union all
select 'Number of customers' as measure_name,count(distinct customer_id) as measure_value from gold.fact_sales
union all
select 'Number of products' as measure_name,count(distinct product_name) as measure_value from gold.dim_products;


/* magnitude analysis*/

-- find total customers by country
select country,count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

-- find total customers by gender
select gender,count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;

-- find total products by category
select category,count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc;

-- find average cost in each category
select category,avg(cost) as average_cost
from gold.dim_products
group by category
order by total_products desc;

-- total revenue generated by each category
select g.category,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_products g
on g.product_key=f.product_key
group by g.category;

-- total revenue generated by each customer 
select g.customer_id,g.first_name,g.last_name,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers g
on g.customer_id=f.customer_id
group by g.customer_id,g.first_name,g.last_name
order by total_revenue desc;

-- what is distribution of sold items across countries
select g.country,sum(f.quantity) as total_sold_items
from gold.fact_sales f 
left join gold.dim_customers g
on g.customer_id=f.customer_id
group by g.country
order by total_sold_items desc;


/* Ranking analysis*/

-- which 5 products generate highest revenue
 select g.product_name,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_products g
on g.product_key=f.product_key
group by g.product_name
order by total_revenue desc
limit 5;

-- which are 5 worst-performing products in terms of sales
 select g.product_name,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_products g
on g.product_key=f.product_key
group by g.product_name
order by total_revenue 
limit 5;

-- find top 10 highest revenue generated customers
select g.customer_id,g.first_name,g.last_name,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers g
on g.customer_id=f.customer_id
where g.customer_id is not null
group by g.customer_id,g.first_name,g.last_name
order by total_revenue desc
limit 10;

-- find 3 lowest performing customers
select g.customer_id,g.first_name,g.last_name,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers g
on g.customer_id=f.customer_id
group by g.customer_id,g.first_name,g.last_name
order by total_revenue 
limit 3;
