/* magnitude analysis*/

-- find total customers by country
select country,count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

-- find total customers by gender
select gender,count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;

-- find total products by category
select category,count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc;

-- find average cost in each category
select category,avg(cost) as average_cost
from gold.dim_products
group by category
order by total_products desc;

-- total revenue generated by each category
select g.category,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_products g
on g.product_key=f.product_key
group by g.category;

-- total revenue generated by each customer 
select g.customer_id,g.first_name,g.last_name,sum(f.sales) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers g
on g.customer_id=f.customer_id
group by g.customer_id,g.first_name,g.last_name
order by total_revenue desc;

-- what is distribution of sold items across countries
select g.country,sum(f.quantity) as total_sold_items
from gold.fact_sales f 
left join gold.dim_customers g
on g.customer_id=f.customer_id
group by g.country
order by total_sold_items desc;

